services:
  frontend:
    image: ghcr.io/benbjd/meowify-web:main
    ports:
      - "3000:3000"
    environment:
      - PYTHON_API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - meowify-network

  api:
    image: ghcr.io/benbjd/meowify-api:main
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoint:/checkpoint
    networks:
      - meowify-network

networks:
  meowify-network:
    driver: bridge 
