version: '3.8'

services:
  frontend:
    image: ghcr.io/benbjd/meowify-web:latest
    ports:
      - "3000:3000"
    environment:
      - PYTHON_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - meowify-network

  api:
    image: ghcr.io/benbjd/meowify-api:latest
    volumes:
      - ./checkpoint:/checkpoint
    networks:
      - meowify-network

networks:
  meowify-network:
    driver: bridge 
